#!/usr/bin/env bash
# notion-docker-compose.sh
# Pulls the Services database from Notion and generates a docker-compose.yml
# file with service definitions.
#
# Requirements:
#   - curl
#   - jq (>= 1.6)
#   - A Notion integration token with read access to the Services database
#
# Usage:
#   NOTION_TOKEN=secret_xxx ./notion-docker-compose.sh
#   NOTION_TOKEN=secret_xxx ./notion-docker-compose.sh --output docker-compose.yml
#   NOTION_TOKEN=secret_xxx ./notion-docker-compose.sh --dry-run

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────

NOTION_TOKEN="${NOTION_TOKEN:-}"
DATABASE_ID=""  # Services database - must be provided by user
NOTION_API="https://api.notion.com/v1"
NOTION_VERSION="2022-06-28"

OUTPUT_FILE=""
DRY_RUN=false

# ── Argument parsing ──────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output|-o)
      OUTPUT_FILE="$2"; shift 2 ;;
    --dry-run|-n)
      DRY_RUN=true; shift ;;
    --token|-t)
      NOTION_TOKEN="$2"; shift 2 ;;
    --database|-d)
      DATABASE_ID="$2"; shift 2 ;;
    --help|-h)
      grep '^#' "$0" | head -20 | sed 's/^# \?//'
      exit 0 ;;
    *)
      echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# ── Preflight checks ──────────────────────────────────────────────────────────

if [[ -z "$NOTION_TOKEN" ]]; then
  echo "ERROR: NOTION_TOKEN is not set." >&2
  echo "       Export it or pass --token secret_xxx" >&2
  exit 1
fi

if [[ -z "$DATABASE_ID" ]]; then
  echo "ERROR: --database <id> is required for Services database." >&2
  echo "       See examples/services-database-template.md for setup." >&2
  exit 1
fi

for cmd in curl jq; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: '$cmd' is required but not found in PATH." >&2
    exit 1
  fi
done

# ── Notion helpers ────────────────────────────────────────────────────────────

notion_query() {
  local db_id="$1"
  local cursor="${2:-}"
  local body

  if [[ -n "$cursor" ]]; then
    body=$(jq -n --arg c "$cursor" '{"start_cursor": $c, "page_size": 100}')
  else
    body='{"page_size": 100}'
  fi

  curl -s -X POST \
    "${NOTION_API}/databases/${db_id}/query" \
    -H "Authorization: Bearer ${NOTION_TOKEN}" \
    -H "Notion-Version: ${NOTION_VERSION}" \
    -H "Content-Type: application/json" \
    -d "$body"
}

# ── Fetch all pages (handles pagination) ──────────────────────────────────────

echo "→ Querying Notion Services database..." >&2

all_results="[]"
cursor=""

while true; do
  response=$(notion_query "$DATABASE_ID" "$cursor")

  # Check for API errors
  if echo "$response" | jq -e '.object == "error"' &>/dev/null; then
    echo "ERROR: Notion API returned an error:" >&2
    echo "$response" | jq -r '.message' >&2
    exit 1
  fi

  page_results=$(echo "$response" | jq '.results')
  all_results=$(jq -n --argjson a "$all_results" --argjson b "$page_results" '$a + $b')

  has_more=$(echo "$response" | jq -r '.has_more')
  [[ "$has_more" == "true" ]] || break
  cursor=$(echo "$response" | jq -r '.next_cursor')
done

total=$(echo "$all_results" | jq 'length')
echo "→ Found ${total} entries." >&2

# ── Extract fields ────────────────────────────────────────────────────────────

# Build an array of objects: {name, image, ports, volumes, environment, network}
services=$(echo "$all_results" | jq '[
  .[] |
  {
    name:        (.properties.Name.title[0].plain_text // "" | ascii_downcase | gsub(" "; "-")),
    image:       (.properties.Image.rich_text[0].plain_text // ""),
    ports:       (.properties.Ports.rich_text[0].plain_text // ""),
    volumes:     (.properties.Volumes.rich_text[0].plain_text // ""),
    environment: (.properties.Environment.rich_text[0].plain_text // ""),
    network:     (.properties.Network.rich_text[0].plain_text // "")
  } |
  select(.name != "" and .image != "")
] | sort_by(.name)')

# ── Generate docker-compose.yml ────────────────────────────────────────────────

generate_compose() {
  local ts
  ts=$(date -u '+%Y-%m-%dT%H:%M:%SZ')

  cat <<EOF
# docker-compose.yml — auto-generated by notion-docker-compose.sh
# Source : Notion Services database (${DATABASE_ID})
# Generated: ${ts}
# DO NOT EDIT BY HAND — regenerate with notion-docker-compose.sh

version: '3.8'

services:
EOF

  # Generate service definitions
  while IFS= read -r entry; do
    name=$(echo "$entry" | jq -r '.name')
    image=$(echo "$entry" | jq -r '.image')
    ports=$(echo "$entry" | jq -r '.ports')
    volumes=$(echo "$entry" | jq -r '.volumes')
    environment=$(echo "$entry" | jq -r '.environment')
    network=$(echo "$entry" | jq -r '.network')

    echo "  ${name}:"
    echo "    image: ${image}"
    echo "    container_name: ${name}"

    # Parse and add ports (format: "8080:80,8443:443" or "3000:3000")
    if [[ -n "$ports" ]]; then
      echo "    ports:"
      IFS=',' read -ra PORT_ARRAY <<< "$ports"
      for port in "${PORT_ARRAY[@]}"; do
        echo "      - \"${port}\""
      done
    fi

    # Parse and add volumes (format: "/host/path:/container/path,/another:/path")
    if [[ -n "$volumes" ]]; then
      echo "    volumes:"
      IFS=',' read -ra VOL_ARRAY <<< "$volumes"
      for vol in "${VOL_ARRAY[@]}"; do
        echo "      - ${vol}"
      done
    fi

    # Parse and add environment variables (format: "KEY=value,KEY2=value2")
    if [[ -n "$environment" ]]; then
      echo "    environment:"
      IFS=',' read -ra ENV_ARRAY <<< "$environment"
      for env in "${ENV_ARRAY[@]}"; do
        echo "      - ${env}"
      done
    fi

    # Add network if specified
    if [[ -n "$network" ]]; then
      echo "    networks:"
      echo "      - ${network}"
    fi

    echo "    restart: unless-stopped"
    echo ""

  done < <(echo "$services" | jq -c '.[]')

  # Add networks section if any service uses networks
  local has_networks
  has_networks=$(echo "$services" | jq -r '[.[].network] | unique | map(select(. != "")) | length')

  if [[ "$has_networks" -gt 0 ]]; then
    echo "networks:"
    echo "$services" | jq -r '[.[].network] | unique | map(select(. != "")) | .[]' | while read -r net; do
      echo "  ${net}:"
      echo "    driver: bridge"
    done
  fi
}

# ── Output ────────────────────────────────────────────────────────────────────

config=$(generate_compose)

if $DRY_RUN; then
  echo "=== DRY RUN — would write: ===" >&2
  echo "$config"
elif [[ -n "$OUTPUT_FILE" ]]; then
  # Backup existing file if present
  if [[ -f "$OUTPUT_FILE" ]]; then
    cp "$OUTPUT_FILE" "${OUTPUT_FILE}.bak"
    echo "→ Backed up existing file to ${OUTPUT_FILE}.bak" >&2
  fi
  echo "$config" > "$OUTPUT_FILE"
  echo "→ Written to ${OUTPUT_FILE}" >&2
  # Validate docker-compose syntax if docker-compose is available
  if command -v docker-compose &>/dev/null || command -v docker &>/dev/null; then
    echo "→ Validating Docker Compose syntax..." >&2
    if docker-compose -f "$OUTPUT_FILE" config >/dev/null 2>&1 || docker compose -f "$OUTPUT_FILE" config >/dev/null 2>&1; then
      echo "→ Docker Compose config is valid." >&2
    else
      echo "WARNING: Docker Compose validation failed." >&2
    fi
  fi
else
  echo "$config"
fi
