#!/usr/bin/env bash
# notion-dnsmasq.sh
# Pulls the Compute database from Notion and generates a dnsmasq.conf
# with static DHCP host entries (dhcp-host) and DNS address entries (address).
#
# Requirements:
#   - curl
#   - jq (>= 1.6)
#   - A Notion integration token with read access to the Compute database
#
# Usage:
#   NOTION_TOKEN=secret_xxx ./notion-dnsmasq.sh
#   NOTION_TOKEN=secret_xxx ./notion-dnsmasq.sh --output /etc/dnsmasq.d/hosts.conf
#   NOTION_TOKEN=secret_xxx ./notion-dnsmasq.sh --dry-run

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────

NOTION_TOKEN="${NOTION_TOKEN:-}"
DATABASE_ID="30b3d6434d24819dbc06e0046b140c30"   # Compute database
NOTION_API="https://api.notion.com/v1"
NOTION_VERSION="2022-06-28"

OUTPUT_FILE=""
DRY_RUN=false

# ── Argument parsing ──────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output|-o)
      OUTPUT_FILE="$2"; shift 2 ;;
    --dry-run|-n)
      DRY_RUN=true; shift ;;
    --token|-t)
      NOTION_TOKEN="$2"; shift 2 ;;
    --database|-d)
      DATABASE_ID="$2"; shift 2 ;;
    --help|-h)
      grep '^#' "$0" | head -20 | sed 's/^# \?//'
      exit 0 ;;
    *)
      echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# ── Preflight checks ──────────────────────────────────────────────────────────

if [[ -z "$NOTION_TOKEN" ]]; then
  echo "ERROR: NOTION_TOKEN is not set." >&2
  echo "       Export it or pass --token secret_xxx" >&2
  exit 1
fi

for cmd in curl jq; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: '$cmd' is required but not found in PATH." >&2
    exit 1
  fi
done

# ── Notion helpers ────────────────────────────────────────────────────────────

notion_query() {
  local db_id="$1"
  local cursor="${2:-}"
  local body

  if [[ -n "$cursor" ]]; then
    body=$(jq -n --arg c "$cursor" '{"start_cursor": $c, "page_size": 100}')
  else
    body='{"page_size": 100}'
  fi

  curl -s -X POST \
    "${NOTION_API}/databases/${db_id}/query" \
    -H "Authorization: Bearer ${NOTION_TOKEN}" \
    -H "Notion-Version: ${NOTION_VERSION}" \
    -H "Content-Type: application/json" \
    -d "$body"
}

# ── Fetch all pages (handles pagination) ──────────────────────────────────────

echo "→ Querying Notion Compute database..." >&2

all_results="[]"
cursor=""

while true; do
  response=$(notion_query "$DATABASE_ID" "$cursor")

  # Check for API errors
  if echo "$response" | jq -e '.object == "error"' &>/dev/null; then
    echo "ERROR: Notion API returned an error:" >&2
    echo "$response" | jq -r '.message' >&2
    exit 1
  fi

  page_results=$(echo "$response" | jq '.results')
  all_results=$(jq -n --argjson a "$all_results" --argjson b "$page_results" '$a + $b')

  has_more=$(echo "$response" | jq -r '.has_more')
  [[ "$has_more" == "true" ]] || break
  cursor=$(echo "$response" | jq -r '.next_cursor')
done

total=$(echo "$all_results" | jq 'length')
echo "→ Found ${total} entries." >&2

# ── Extract fields ────────────────────────────────────────────────────────────

# Build an array of objects: {name, ip, mac}
# Notion rich_text / title properties return arrays; we take the plain_text of [0].
hosts=$(echo "$all_results" | jq '[
  .[] |
  {
    name: (.properties.Name.title[0].plain_text // "" | ascii_downcase | gsub(" "; "-")),
    ip:   (.properties.IP.rich_text[0].plain_text // ""),
    mac:  (.properties.MAC.rich_text[0].plain_text // "")
  } |
  select(.name != "")
] | sort_by(.name)')

# ── Generate dnsmasq config ───────────────────────────────────────────────────

generate_config() {
  local ts
  ts=$(date -u '+%Y-%m-%dT%H:%M:%SZ')

  cat <<EOF
# dnsmasq.conf — auto-generated by notion-dnsmasq.sh
# Source : Notion Compute database (${DATABASE_ID})
# Generated: ${ts}
# DO NOT EDIT BY HAND — regenerate with notion-dnsmasq.sh
#
# Entries with both MAC + IP → dhcp-host (static DHCP lease)
# Entries with IP only       → address   (DNS A record only)
# Entries with neither       → skipped

EOF

  local dhcp_section=""
  local dns_section=""
  local skipped=0

  while IFS= read -r entry; do
    name=$(echo "$entry" | jq -r '.name')
    ip=$(echo "$entry" | jq -r '.ip')
    mac=$(echo "$entry" | jq -r '.mac')

    # Normalise MAC to lowercase colon-separated if present
    if [[ -n "$mac" ]]; then
      mac=$(echo "$mac" | tr '[:upper:]' '[:lower:]' | \
            sed 's/-/:/g' | \
            sed 's/[^0-9a-f:]//g')
    fi

    if [[ -n "$mac" && -n "$ip" ]]; then
      # Static DHCP binding + DNS
      dhcp_section+="dhcp-host=${mac},${name},${ip}\n"
      dns_section+="address=/${name}/${ip}\n"
    elif [[ -n "$ip" ]]; then
      # DNS-only (no MAC for DHCP)
      dns_section+="address=/${name}/${ip}\n"
    else
      (( skipped++ )) || true
      echo "# SKIP: ${name} — no IP or MAC recorded" >&2
    fi
  done < <(echo "$hosts" | jq -c '.[]')

  if [[ -n "$dhcp_section" ]]; then
    printf "# ── Static DHCP leases ───────────────────────────────────────────────────────\n"
    printf "# dhcp-host=<mac>,<hostname>,<ip>\n\n"
    printf "%b\n" "$dhcp_section"
  fi

  if [[ -n "$dns_section" ]]; then
    printf "# ── DNS address records ─────────────────────────────────────────────────────\n"
    printf "# address=/<hostname>/<ip>\n\n"
    printf "%b\n" "$dns_section"
  fi

  echo "→ Skipped ${skipped} entries (no IP/MAC)." >&2
}

# ── Output ────────────────────────────────────────────────────────────────────

config=$(generate_config)

if $DRY_RUN; then
  echo "=== DRY RUN — would write: ===" >&2
  echo "$config"
elif [[ -n "$OUTPUT_FILE" ]]; then
  # Backup existing file if present
  if [[ -f "$OUTPUT_FILE" ]]; then
    cp "$OUTPUT_FILE" "${OUTPUT_FILE}.bak"
    echo "→ Backed up existing file to ${OUTPUT_FILE}.bak" >&2
  fi
  echo "$config" > "$OUTPUT_FILE"
  echo "→ Written to ${OUTPUT_FILE}" >&2
  # Reload dnsmasq if running
  if command -v systemctl &>/dev/null && systemctl is-active --quiet dnsmasq 2>/dev/null; then
    echo "→ Reloading dnsmasq..." >&2
    systemctl reload dnsmasq && echo "→ dnsmasq reloaded." >&2 || echo "WARNING: reload failed." >&2
  fi
else
  echo "$config"
fi
