#!/usr/bin/env bash
# notion-nginx.sh
# Pulls the Services database from Notion and generates nginx reverse proxy
# configuration with server blocks for each service.
#
# Requirements:
#   - curl
#   - jq (>= 1.6)
#   - A Notion integration token with read access to the Services database
#
# Usage:
#   NOTION_TOKEN=secret_xxx ./notion-nginx.sh
#   NOTION_TOKEN=secret_xxx ./notion-nginx.sh --output /etc/nginx/conf.d/services.conf
#   NOTION_TOKEN=secret_xxx ./notion-nginx.sh --dry-run

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────

NOTION_TOKEN="${NOTION_TOKEN:-}"
DATABASE_ID=""  # Services database - must be provided by user
NOTION_API="https://api.notion.com/v1"
NOTION_VERSION="2022-06-28"

OUTPUT_FILE=""
DRY_RUN=false

# ── Argument parsing ──────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output|-o)
      OUTPUT_FILE="$2"; shift 2 ;;
    --dry-run|-n)
      DRY_RUN=true; shift ;;
    --token|-t)
      NOTION_TOKEN="$2"; shift 2 ;;
    --database|-d)
      DATABASE_ID="$2"; shift 2 ;;
    --help|-h)
      grep '^#' "$0" | head -20 | sed 's/^# \?//'
      exit 0 ;;
    *)
      echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# ── Preflight checks ──────────────────────────────────────────────────────────

if [[ -z "$NOTION_TOKEN" ]]; then
  echo "ERROR: NOTION_TOKEN is not set." >&2
  echo "       Export it or pass --token secret_xxx" >&2
  exit 1
fi

if [[ -z "$DATABASE_ID" ]]; then
  echo "ERROR: --database <id> is required for Services database." >&2
  echo "       See examples/services-database-template.md for setup." >&2
  exit 1
fi

for cmd in curl jq; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: '$cmd' is required but not found in PATH." >&2
    exit 1
  fi
done

# ── Notion helpers ────────────────────────────────────────────────────────────

notion_query() {
  local db_id="$1"
  local cursor="${2:-}"
  local body

  if [[ -n "$cursor" ]]; then
    body=$(jq -n --arg c "$cursor" '{"start_cursor": $c, "page_size": 100}')
  else
    body='{"page_size": 100}'
  fi

  curl -s -X POST \
    "${NOTION_API}/databases/${db_id}/query" \
    -H "Authorization: Bearer ${NOTION_TOKEN}" \
    -H "Notion-Version: ${NOTION_VERSION}" \
    -H "Content-Type: application/json" \
    -d "$body"
}

# ── Fetch all pages (handles pagination) ──────────────────────────────────────

echo "→ Querying Notion Services database..." >&2

all_results="[]"
cursor=""

while true; do
  response=$(notion_query "$DATABASE_ID" "$cursor")

  # Check for API errors
  if echo "$response" | jq -e '.object == "error"' &>/dev/null; then
    echo "ERROR: Notion API returned an error:" >&2
    echo "$response" | jq -r '.message' >&2
    exit 1
  fi

  page_results=$(echo "$response" | jq '.results')
  all_results=$(jq -n --argjson a "$all_results" --argjson b "$page_results" '$a + $b')

  has_more=$(echo "$response" | jq -r '.has_more')
  [[ "$has_more" == "true" ]] || break
  cursor=$(echo "$response" | jq -r '.next_cursor')
done

total=$(echo "$all_results" | jq 'length')
echo "→ Found ${total} entries." >&2

# ── Extract fields ────────────────────────────────────────────────────────────

# Build an array of objects: {name, domain, backend, port, ssl}
services=$(echo "$all_results" | jq '[
  .[] |
  {
    name:    (.properties.Name.title[0].plain_text // "" | ascii_downcase | gsub(" "; "-")),
    domain:  (.properties.Domain.rich_text[0].plain_text // ""),
    backend: (.properties.Backend.rich_text[0].plain_text // ""),
    port:    (.properties.Port.number // 80),
    ssl:     (.properties.SSL.checkbox // false)
  } |
  select(.name != "" and .domain != "" and .backend != "")
] | sort_by(.domain)')

# ── Generate nginx config ──────────────────────────────────────────────────────

generate_nginx_config() {
  local ts
  ts=$(date -u '+%Y-%m-%dT%H:%M:%SZ')

  cat <<EOF
# nginx-services.conf — auto-generated by notion-nginx.sh
# Source : Notion Services database (${DATABASE_ID})
# Generated: ${ts}
# DO NOT EDIT BY HAND — regenerate with notion-nginx.sh

EOF

  # Generate server block for each service
  while IFS= read -r entry; do
    name=$(echo "$entry" | jq -r '.name')
    domain=$(echo "$entry" | jq -r '.domain')
    backend=$(echo "$entry" | jq -r '.backend')
    port=$(echo "$entry" | jq -r '.port')
    ssl=$(echo "$entry" | jq -r '.ssl')

    echo "# ${name}"
    echo "server {"

    if [[ "$ssl" == "true" ]]; then
      echo "    listen 443 ssl http2;"
      echo "    listen [::]:443 ssl http2;"
      echo "    server_name ${domain};"
      echo ""
      echo "    ssl_certificate /etc/ssl/certs/${name}.crt;"
      echo "    ssl_certificate_key /etc/ssl/private/${name}.key;"
      echo ""
      echo "    # Modern SSL configuration"
      echo "    ssl_protocols TLSv1.2 TLSv1.3;"
      echo "    ssl_prefer_server_ciphers off;"
      echo "    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;"
    else
      echo "    listen ${port};"
      echo "    listen [::]:${port};"
      echo "    server_name ${domain};"
    fi

    echo ""
    echo "    location / {"
    echo "        proxy_pass ${backend};"
    echo "        proxy_set_header Host \$host;"
    echo "        proxy_set_header X-Real-IP \$remote_addr;"
    echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
    echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
    echo "    }"
    echo "}"
    echo ""

    # Add HTTP -> HTTPS redirect if SSL is enabled
    if [[ "$ssl" == "true" ]]; then
      echo "# ${name} HTTP redirect"
      echo "server {"
      echo "    listen 80;"
      echo "    listen [::]:80;"
      echo "    server_name ${domain};"
      echo "    return 301 https://\$server_name\$request_uri;"
      echo "}"
      echo ""
    fi

  done < <(echo "$services" | jq -c '.[]')
}

# ── Output ────────────────────────────────────────────────────────────────────

config=$(generate_nginx_config)

if $DRY_RUN; then
  echo "=== DRY RUN — would write: ===" >&2
  echo "$config"
elif [[ -n "$OUTPUT_FILE" ]]; then
  # Backup existing file if present
  if [[ -f "$OUTPUT_FILE" ]]; then
    cp "$OUTPUT_FILE" "${OUTPUT_FILE}.bak"
    echo "→ Backed up existing file to ${OUTPUT_FILE}.bak" >&2
  fi
  echo "$config" > "$OUTPUT_FILE"
  echo "→ Written to ${OUTPUT_FILE}" >&2
  # Test nginx config
  if command -v nginx &>/dev/null; then
    echo "→ Testing nginx configuration..." >&2
    if nginx -t 2>&1 | grep -q "successful"; then
      echo "→ nginx config test passed." >&2
      # Reload nginx if running
      if command -v systemctl &>/dev/null && systemctl is-active --quiet nginx 2>/dev/null; then
        echo "→ Reloading nginx..." >&2
        systemctl reload nginx && echo "→ nginx reloaded." >&2 || echo "WARNING: reload failed." >&2
      fi
    else
      echo "WARNING: nginx config test failed. Not reloading." >&2
    fi
  fi
else
  echo "$config"
fi
